/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/[...catch]': RouteRecordInfo<'/[...catch]', '/:catch(.*)', { catch: ParamValue<true> }, { catch: ParamValue<false> }>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/contact/[org_num]/add-device-[dept_id]-[dept_name]': RouteRecordInfo<'/contact/[org_num]/add-device-[dept_id]-[dept_name]', '/contact/:org_num/add-device-:dept_id-:dept_name', { org_num: ParamValue<true>, dept_id: ParamValue<true>, dept_name: ParamValue<true> }, { org_num: ParamValue<false>, dept_id: ParamValue<false>, dept_name: ParamValue<false> }>,
    '/contact/[org_num]/add-member-[dept_id]-[dept_name]': RouteRecordInfo<'/contact/[org_num]/add-member-[dept_id]-[dept_name]', '/contact/:org_num/add-member-:dept_id-:dept_name', { org_num: ParamValue<true>, dept_id: ParamValue<true>, dept_name: ParamValue<true> }, { org_num: ParamValue<false>, dept_id: ParamValue<false>, dept_name: ParamValue<false> }>,
    '/contact/[org_num]/dept-[dept_id]': RouteRecordInfo<'/contact/[org_num]/dept-[dept_id]', '/contact/:org_num/dept-:dept_id', { org_num: ParamValue<true>, dept_id: ParamValue<true> }, { org_num: ParamValue<false>, dept_id: ParamValue<false> }>,
    '/contact/[org_num]/details': RouteRecordInfo<'/contact/[org_num]/details', '/contact/:org_num/details', { org_num: ParamValue<true> }, { org_num: ParamValue<false> }>,
    '/contact/[org_num]/edit-device-[dept_id]-[user_id]': RouteRecordInfo<'/contact/[org_num]/edit-device-[dept_id]-[user_id]', '/contact/:org_num/edit-device-:dept_id-:user_id', { org_num: ParamValue<true>, dept_id: ParamValue<true>, user_id: ParamValue<true> }, { org_num: ParamValue<false>, dept_id: ParamValue<false>, user_id: ParamValue<false> }>,
    '/contact/[org_num]/edit-member-[dept_id]-[user_id]': RouteRecordInfo<'/contact/[org_num]/edit-member-[dept_id]-[user_id]', '/contact/:org_num/edit-member-:dept_id-:user_id', { org_num: ParamValue<true>, dept_id: ParamValue<true>, user_id: ParamValue<true> }, { org_num: ParamValue<false>, dept_id: ParamValue<false>, user_id: ParamValue<false> }>,
    '/contact/[org_num]/member-[dept_id]-[user_id]': RouteRecordInfo<'/contact/[org_num]/member-[dept_id]-[user_id]', '/contact/:org_num/member-:dept_id-:user_id', { org_num: ParamValue<true>, dept_id: ParamValue<true>, user_id: ParamValue<true> }, { org_num: ParamValue<false>, dept_id: ParamValue<false>, user_id: ParamValue<false> }>,
    '/contact/group': RouteRecordInfo<'/contact/group', '/contact/group', Record<never, never>, Record<never, never>>,
    '/contact/org': RouteRecordInfo<'/contact/org', '/contact/org', Record<never, never>, Record<never, never>>,
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>>,
    '/me/': RouteRecordInfo<'/me/', '/me', Record<never, never>, Record<never, never>>,
    '/me/binding-phone': RouteRecordInfo<'/me/binding-phone', '/me/binding-phone', Record<never, never>, Record<never, never>>,
    '/me/reset-password': RouteRecordInfo<'/me/reset-password', '/me/reset-password', Record<never, never>, Record<never, never>>,
    '/message': RouteRecordInfo<'/message', '/message', Record<never, never>, Record<never, never>>,
    '/message/[group_id]-[group_name]': RouteRecordInfo<'/message/[group_id]-[group_name]', '/message/:group_id-:group_name', { group_id: ParamValue<true>, group_name: ParamValue<true> }, { group_id: ParamValue<false>, group_name: ParamValue<false> }>,
    '/not-found/': RouteRecordInfo<'/not-found/', '/not-found', Record<never, never>, Record<never, never>>,
    '/redirect/': RouteRecordInfo<'/redirect/', '/redirect', Record<never, never>, Record<never, never>>,
    '/register/': RouteRecordInfo<'/register/', '/register', Record<never, never>, Record<never, never>>,
    '/workbench/': RouteRecordInfo<'/workbench/', '/workbench', Record<never, never>, Record<never, never>>,
  }
}
