/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarUploader: typeof import('./components/AvatarUploader.vue')['default']
    Block: typeof import('./components/global-setting/block.vue')['default']
    Breadcrumb: typeof import('./components/breadcrumb/index.vue')['default']
    Chart: typeof import('./components/chart/index.vue')['default']
    DialogClose: typeof import('radix-vue')['DialogClose']
    DialogContent: typeof import('radix-vue')['DialogContent']
    DialogDescription: typeof import('radix-vue')['DialogDescription']
    DialogOverlay: typeof import('radix-vue')['DialogOverlay']
    DialogPortal: typeof import('radix-vue')['DialogPortal']
    DialogRoot: typeof import('radix-vue')['DialogRoot']
    DialogTitle: typeof import('radix-vue')['DialogTitle']
    DialogTrigger: typeof import('radix-vue')['DialogTrigger']
    Footer: typeof import('./components/footer/index.vue')['default']
    FormWrapper: typeof import('./components/global-setting/form-wrapper.vue')['default']
    GlobalSetting: typeof import('./components/global-setting/index.vue')['default']
    List: typeof import('./components/message-box/list.vue')['default']
    ListboxContent: typeof import('radix-vue')['ListboxContent']
    ListboxGroup: typeof import('radix-vue')['ListboxGroup']
    ListboxGroupLabel: typeof import('radix-vue')['ListboxGroupLabel']
    ListboxItem: typeof import('radix-vue')['ListboxItem']
    ListboxItemIndicator: typeof import('radix-vue')['ListboxItemIndicator']
    ListboxRoot: typeof import('radix-vue')['ListboxRoot']
    LoginBanner: typeof import('./components/login-banner/index.vue')['default']
    MemberList: typeof import('./components/MemberList.vue')['default']
    Menu: typeof import('./components/menu/index.vue')['default']
    MessageBox: typeof import('./components/message-box/index.vue')['default']
    Navbar: typeof import('./components/navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VerifyImg: typeof import('./components/VerifyImg.vue')['default']
  }
}
