/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarUploader: typeof import('./components/AvatarUploader.vue')['default']
    Block: typeof import('./components/global-setting/block.vue')['default']
    Breadcrumb: typeof import('./components/breadcrumb/index.vue')['default']
    Chart: typeof import('./components/chart/index.vue')['default']
    Footer: typeof import('./components/footer/index.vue')['default']
    FormWrapper: typeof import('./components/global-setting/form-wrapper.vue')['default']
    GlobalSetting: typeof import('./components/global-setting/index.vue')['default']
    List: typeof import('./components/message-box/list.vue')['default']
    LoginBanner: typeof import('./components/login-banner/index.vue')['default']
    MemberList: typeof import('./components/MemberList.vue')['default']
    Menu: typeof import('./components/menu/index.vue')['default']
    MessageBox: typeof import('./components/message-box/index.vue')['default']
    Navbar: typeof import('./components/navbar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VerifyImg: typeof import('./components/VerifyImg.vue')['default']
  }
}
